### ISSUE TITLE
Literal strings aren't highlighted correctly when using [=[ ... ]=] syntax

### ISSUE THREAD

**Issue by SkyyySi** [pigpigyyy/yuescript-vscode#2]
When writing a literal string using angle brackets with equals signs in between, it gets incorrectly highlighted, as shown in the screenshot below.

![grafic](https://github.com/pigpigyyy/yuescript-vscode/assets/53921371/7d2ef5da-af43-4c3a-a1b6-6280fe6ddac0)

**Comment by SkyyySi** [comment]
This can be fixed by adding a capture for `=*` in the definition of multiline strings:

```js
// file: /syntaxes/yuescript.tmLanguage.json
// line: 72
{
	"begin": "\\[(=*)\\[",
	"beginCaptures": {
		"0": {
			"name": "punctuation.definition.string.begin.yue"
		}
	},
	"end": "\\]\\1\\]",
	"endCaptures": {
		"0": {
			"name": "punctuation.definition.string.end.yue"
		}
	},
	"name": "string.quoted.other.multiline.yue"
},
```

![grafic](https://github.com/pigpigyyy/yuescript-vscode/assets/53921371/623defbe-7241-43b2-8081-9e57c9e651a0)

**Comment by pigpigyyy** [comment]
Thanks for your fix! Got vsc plugin fixed and updated!
