### ISSUE TITLE
Highlighting const and close variable declarations

### ISSUE THREAD

**Issue by SkyyySi** [pigpigyyy/yuescript-vscode#3]
Yuescript supports using `const` and `close` to declare variables, so they should also get highlighted. However, since they aren't fully reserved keywords, they should only be highlighted when actually used as a declaration. This could be detected by a regex pattern like this (untested):

```regex
(close|const)\s+[a-zA-Z_][a-zA-Z0-9_]*
```

**Comment by pigpigyyy** [comment]
fixed by PR #4.
